export const GENETIC_PROFILE_MUTATIONS_SUFFIX = '_mutations';
export const GENETIC_PROFILE_UNCALLED_MUTATIONS_SUFFIX = `${GENETIC_PROFILE_MUTATIONS_SUFFIX}_uncalled`;
export const GENETIC_PROFILE_MRNA_EXPRESSION='MRNA_EXPRESSION';
